name = "bolo"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[vars]
GITHUB_REPO = "bolo"

# Add these secrets via: wrangler secret put GITHUB_TOKEN
# Add these secrets via: wrangler secret put GITHUB_OWNER

[[kv_namespaces]]
binding = "BOLO_KV"
id = "23e533156f824dc7a11efeb28bf467b3"
